{
 "title": "RGW S3 Analytics",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_metadata{cluster=~\"$cluster\", }, ceph_daemon)"
   },
   { "name": "Filters", "label": "filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total PUTs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_rgw_op_put_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GETs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\n(ceph_rgw_op_get_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_rgw_op_put_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Object Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\n((sum by(instance_id)(ceph_rgw_op_put_obj_bytes) > 0) / (sum by(instance_id)(ceph_rgw_op_put_obj_ops) > 0) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_rgw_op_list_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "List Objects"
    },
    {
     "expr": "sum(ceph_rgw_op_list_buckets_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "List Buckets"
    },
    {
     "expr": "sum(ceph_rgw_op_put_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Put Objects"
    },
    {
     "expr": "sum(ceph_rgw_op_per_bucket_get_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Get Objects"
    },
    {
     "expr": "sum(ceph_rgw_op_del_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Delete Objects"
    },
    {
     "expr": "sum(ceph_rgw_op_del_bucket_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Delete Buckets"
    },
    {
     "expr": "sum(ceph_rgw_op_copy_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Copy Objects"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_rgw_op_put_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Put Objects"
    },
    {
     "expr": "sum(ceph_rgw_op_per_bucket_get_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Get Objects"
    },
    {
     "expr": "sum(ceph_rgw_op_del_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Delete Objects"
    },
    {
     "expr": "sum(ceph_rgw_op_copy_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Copy Objects"
    }
   ]
  },
  {
   "title": "Total Latencies",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_rgw_op_list_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "List Object"
    },
    {
     "expr": "sum(ceph_rgw_op_list_buckets_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "List Bucket"
    },
    {
     "expr": "sum(ceph_rgw_op_put_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Put Object"
    },
    {
     "expr": "sum(ceph_rgw_op_get_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Get Object"
    },
    {
     "expr": "sum(ceph_rgw_op_del_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Delete Object"
    },
    {
     "expr": "sum(ceph_rgw_op_del_bucket_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Delete Bucket"
    },
    {
     "expr": "sum(ceph_rgw_op_copy_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Copy Object"
    }
   ]
  },
  {
   "title": "Summary Per Bucket by Bandwidth",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_put_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Upload Objects"
    },
    {
     "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_get_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Get Objects"
    },
    {
     "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_del_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Delete Objects"
    },
    {
     "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_copy_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
     "legendFormat": "Copy Objects"
    }
   ]
  },
  {
   "title": "Latency(ms) Per Bucket",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "ceph_rgw_op_per_bucket_list_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "List Objects"
    },
    {
     "expr": "ceph_rgw_op_per_bucket_put_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Upload Objects"
    },
    {
     "expr": "ceph_rgw_op_per_bucket_get_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Get Objects"
    },
    {
     "expr": "ceph_rgw_op_per_bucket_del_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Delete Objects"
    },
    {
     "expr": "ceph_rgw_op_per_bucket_copy_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Copy Objects"
    }
   ]
  },
  {
   "title": "Summary Per User By Bandwidth",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ceph_rgw_op_per_user_put_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Upload Objects"
    },
    {
     "expr": "ceph_rgw_op_per_user_get_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Get Objects"
    },
    {
     "expr": "ceph_rgw_op_per_user_del_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Delete Objects"
    },
    {
     "expr": "ceph_rgw_op_per_user_copy_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "Copy Objects"
    }
   ]
  },
  {
   "title": "Latency(ms) Per User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "ceph_rgw_op_per_user_list_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_rgw_op_per_user_put_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_rgw_op_per_user_get_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_rgw_op_per_user_del_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_rgw_op_per_user_copy_obj_lat_sum *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Bucket PUTs by Operations",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, \n    sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_put_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Top 5 Bucket GETs by Operations",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, \n    sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_get_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Top 5 Buckets PUTs By Size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "topk(5,\n    sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_put_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Top 5 Buckets GETs By Size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
     "targets": [
      {
       "expr": "topk(5,\n    sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_get_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket PUTs by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_put_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket GETs by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_get_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket Copy by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_copy_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket Delete by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_del_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket GETs by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_get_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket PUTs by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_put_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket List by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_list_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket Delete by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_del_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket Copy by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) ((ceph_rgw_op_per_bucket_copy_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{bucket}}"
      }
     ]
    },
    {
     "title": "Summary Per Bucket by Operations",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_put_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_get_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_del_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_copy_obj_bytes *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (bucket, ceph_daemon) (ceph_rgw_op_per_bucket_list_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Users PUTs By Operations",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, \n    sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_put_obj_ops ) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)\n",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "Top 5 Users GETs by Operations",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, \n    sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_get_obj_ops ) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)\n",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "Top 5 Users PUTs by Size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "topk(5, \n    sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_put_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "Top 5 Users GETs By Size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 62 },
     "targets": [
      {
       "expr": "topk(5, \n    sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_get_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })\n)",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User PUTs by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_put_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User GETs by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_get_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User Delete by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_del_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User COPY by Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_copy_obj_bytes) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User GETs by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_get_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User PUTs by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_put_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User List by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_list_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User Delete by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_del_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "User Copy by Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) ((ceph_rgw_op_per_user_copy_obj_ops) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "{{ceph_daemon}} - {{user}}"
      }
     ]
    },
    {
     "title": "Summary Per User By Operations",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "sum by (user, ceph_daemon) (ceph_rgw_op_per_user_put_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (user, ceph_daemon) (ceph_rgw_op_per_user_get_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (user, ceph_daemon) (ceph_rgw_op_per_user_del_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (user, ceph_daemon) (ceph_rgw_op_per_user_copy_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (user, ceph_daemon) (ceph_rgw_op_per_user_list_obj_ops *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", })",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}